# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Typestream < Formula
  desc "TypeStream CLI & toolbox"
  homepage "https://typestream.io"
  version "2023.08.31+3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/typestreamio/homebrew-tap/releases/download/2023.08.31+3/typestream_Darwin_arm64.tar.gz"
      sha256 "9c896f2d37f6c64a9800cab284a7838c67d3b46799e94a7725365c188c14fbc3"

      def install
        bin.install "typestream"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/typestreamio/homebrew-tap/releases/download/2023.08.31+3/typestream_Darwin_x86_64.tar.gz"
      sha256 "21855023946e3bd157e3c9728ed25b955060faa8f708c160fa2a4b518b431c0e"

      def install
        bin.install "typestream"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/typestreamio/homebrew-tap/releases/download/2023.08.31+3/typestream_Linux_arm64.tar.gz"
      sha256 "ae0e990c16c7e7cd39c52c0489c7e52dc9179341f9cc547443949562679389d9"

      def install
        bin.install "typestream"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/typestreamio/homebrew-tap/releases/download/2023.08.31+3/typestream_Linux_x86_64.tar.gz"
      sha256 "5481013fb4364b449a389faf3ee7189ded302ca6c4e4d735b2f73693505a8a88"

      def install
        bin.install "typestream"
      end
    end
  end
end
