# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Typestream < Formula
  desc "TypeStream CLI & toolbox"
  homepage "https://typestream.io"
  version "2023.08.31+2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/typestreamio/homebrew-tap/releases/download/2023.08.31+2/typestream_Darwin_arm64.tar.gz"
      sha256 "4b3b5c3df9daaddc20c0fcbbb0dc4965043f5ea97ccaac99e73bdf599de4bf0a"

      def install
        bin.install "typestream"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/typestreamio/homebrew-tap/releases/download/2023.08.31+2/typestream_Darwin_x86_64.tar.gz"
      sha256 "facdc075e947a9258a34c1d98f1a235b1e2dffa439eeadbacb697c1859afe89b"

      def install
        bin.install "typestream"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/typestreamio/homebrew-tap/releases/download/2023.08.31+2/typestream_Linux_arm64.tar.gz"
      sha256 "b72fab24133c8d8546009e1382c735aabf75d64a6d7dbccfae641564afa9dbdf"

      def install
        bin.install "typestream"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/typestreamio/homebrew-tap/releases/download/2023.08.31+2/typestream_Linux_x86_64.tar.gz"
      sha256 "f8f380065bff66a983307cb5dba54ee9db63c0b1b1be68def9f8ddf34af4955c"

      def install
        bin.install "typestream"
      end
    end
  end
end
